name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
      - run: sudo npm install -g typescript nyc mocha
      - run: npm install
      - run: npm run build
      - run: npm run test
      
